### ISSUE TITLE
Cannot print anything

### ISSUE THREAD

**Issue by sanchi3** [elvishew/xLog#10]
Gradle:2.2.2
Debug build

I compiled this library in my project's library module.
And init it in my application by `XLog.init(BuildConfig.DEBUG ? LogLevel.ALL : LogLevel.NONE, new LogConfiguration.Builder().t().b().build());`.
The library module is compiled by `compile project(':library')` in gradle file.My application is registered correctly in `AndroidManifest.xml`.
But it cannot print anything in activity when invoke `XLog.d(msg);`.
What's wrong?Thx.

**Comment by elvishew** [comment]
@sanchi3 Can you tell which package the `BuildConfig` from? It should be from your app's package, not from other module or library.

I think `BuildConfig.DEBUG` is false in your environment, please check it first.

**Comment by sanchi3** [comment]
Emmm... you are right,it's my fault.Thank you very much.
