### ISSUE TITLE
xLog should not crash app but give helpful hints when there in an invalid Json

### ISSUE THREAD

**Issue by shipsywor** [elvishew/xLog#103]
When the json is invalid, xLog crashes the Android app and gives error "format parse ..."

Instead of doing that it should either give helpful validation errors like this site: https://jsonformatter.curiousconcept.com/#

Or simply print in the logcat that the "json is invalid". The App should NOT crash.

This is what https://github.com/orhanobut/logger does:

The important part is that App is not crashed!

![k_2021-06-12_20-18-34](https://user-images.githubusercontent.com/67386890/121774373-3007b100-cbbd-11eb-8831-a7c68d260e17.png)

Please think of a more thoughtful way of dealing with invalid json errors. Crashing the app is very inconvenient.

**Comment by elvishew** [comment]
@shipsywor Thanks for your reasonable suggestion, will do it.

**Comment by elvishew** [comment]
v1.10.0 is released, close
