### ISSUE TITLE
荣耀平板5 P版本 无法在Context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)的目录下创建文件---事实上任何文件夹都创建不了日志文件

### ISSUE THREAD

**Issue by Huymee** [elvishew/xLog#105]

**Comment by elvishew** [comment]
@Huymee Do you mean that in your device, `"sdcard/Android/data/<packageName>/files/Documents/<logFolder>"` is empty?

I test in my side with
```
Printer filePrinter = new FilePrinter
        .Builder(new File(getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "log").getPath())
        ...
```
it works for me.

What if you try it on another device? Maybe there is something different in "荣耀平板5 P版本".

**Comment by Huymee** [comment]
在其它设备上几乎都能工作，我试过了小米mix2（P版本） 小米mix2（Q版本）联想平板（Q版本）等一系列设备（没有测试除荣耀平板5以外的华为设备），但是只有荣耀平板5无法创建日志文件

**Comment by elvishew** [comment]
> 在其它设备上几乎都能工作，我试过了小米mix2（P版本） 小米mix2（Q版本）联想平板（Q版本）等一系列设备（没有测试除荣耀平板5以外的华为设备），但是只有荣耀平板5无法创建日志文件

@Huymee Seems it is a device-specific issue.

Can you run `logcat -s System.err` to see the failure info? If an exception occurred during logging to file, it may print the failure reason to the terminal.

If still no failure info in the terminal, maybe you can download the source code and debug the `FilePrinter.doPrintln` to see where it fails.

**Comment by Huymee** [comment]
好的 目前设备不在我手上，过两天我把设备拿到之后再来试试，刚刚我又借到一台8.0版本和和一台7.1版本的华为手机，验证都没问题

**Comment by Huymee** [comment]
我拿到设备了，经过反复调试之后发现了问题----运行时权限逻辑存在问题，重新梳理一遍之后就ok了。感谢作者！！！！
另外提一个建议，可以考虑把打日志的线程号和进程号打印出来，方便定位问题
