### ISSUE TITLE
主动删除日志文件

### ISSUE THREAD

**Issue by Star3513** [elvishew/xLog#113]
请问可以主动删除某个日志文件吗

**Comment by Rockets1080** [comment]
有清除日志缓存策略的，我配置供你参考

 Printer filePrinter = new FilePrinter                      // Printer that print the log to the file system
                .Builder(new File(context.getExternalCacheDir().getAbsolutePath(), "log").getPath())       // Specify the path to save log file
                .fileNameGenerator(new FileNameGenerator() {
                    @Override
                    public boolean isFileNameChangeable() {
                        return true;
                    }

                    @Override
                    public String generateFileName(int logLevel, long timestamp) {
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.CHINESE);
                        sdf.setTimeZone(TimeZone.getDefault());
                        return sdf.format(new Date(timestamp))+".txt";
                    }
                })        // Default: ChangelessFileNameGenerator("log")
                .backupStrategy(new FileSizeBackupStrategy2(MAX_SIZE,MAX_BACKUP_INDEX))             // Default: FileSizeBackupStrategy(1024 * 1024)
                .cleanStrategy(new FileLastModifiedCleanStrategy(MAX_CLEAN_TIME))     // Default: NeverCleanStrategy()
                .flattener(new ClassicFlattener())                     // Default: DefaultFlattener
                .writer(new SimpleWriter() {                           // Default: SimpleWriter
                    @Override
                    public void onNewFileCreated(File file) {
                        super.onNewFileCreated(file);
                        final String header = "\n>>>>>>>>>>>>>>>> File Header >>>>>>>>>>>>>>>>" +
                                "\nDevice Manufacturer: " + Build.MANUFACTURER +
                                "\nDevice Model       : " + Build.MODEL +
                                "\nAndroid Version    : " + Build.VERSION.RELEASE +
                                "\nAndroid SDK        : " + Build.VERSION.SDK_INT +
                                "\nApp VersionName    : " + getVersionName(context) +
                                "\nApp VersionCode    : " + getVersionCode(context) +
                                "\n<<<<<<<<<<<<<<<< File Header <<<<<<<<<<<<<<<<\n\n";
                        appendLog(header);
                    }
                })
                .build();

**Comment by Rockets1080** [comment]
public static long MAX_CLEAN_TIME = 7 * 24 * 60 * 60 * 1000;//最大清理时间，自动删掉那些一段时间（如：一周）以来都未被修改的日志文件

**Comment by Star3513** [comment]
@Rockets1080 好的，多谢回答
