### ISSUE TITLE
多个module中如何分别统计日志到app-log,xtools-log呢？

### ISSUE THREAD

**Issue by ichtj** [elvishew/xLog#123]
hi
项目中碰到一个问题，我除了app Module之外，还有一个xTools Module,现在想记录日志到两个文件，app Module依赖xTools
另外该在哪个module中进行初始化XLog呢？
我是现在app Module初始化了，xTools也进行了初始化，日志能记录，但是发现xTools初始化XLog覆盖了一些参数，导致日志都是往xtools-log中写的，没有实现分别统计
请问有什么办法吗？

**Comment by elvishew** [comment]
要记录到不同文件，可使用不同的 Logger 实例。如在 xTools 里定义一个写到 xtools-log 的 Logger，在 app module 里定义另一个写日志到 app-log 的 Logger。

**Comment by ichtj** [comment]
XTools Module

`public class XTools {
    private static volatile XTools sInstance;
    private static final long MAX_TIME = 1L * 24L * 60L * 60L * 1000L;
    private Logger xToolLogger;
    
    public Logger getxToolLogger() {
        return xToolLogger;
    }

    public void setxToolLogger(Logger xToolLogger) {
        this.xToolLogger = xToolLogger;
    }

    //单例模式
    public static XTools instance() {
        if (sInstance == null) {
            synchronized (XTools.class) {
                if (sInstance == null) {
                    sInstance = new XTools();
                }
            }
        }
        return sInstance;
    }

    public XTools() {
        String xlogPath = "/sdcard/applog/log2/";
        Printer filePrinter = new FilePrinter                      // Printer that print(save) the log to file 打印(保存)日志到文件的打印机
                .Builder(xlogPath)                         // Specify the directory path of log file(s) 指定日志文件的目录路径
                .fileNameGenerator(new DateFileNameGenerator())        // Default: ChangelessFileNameGenerator("log") 默认值:ChangelessFileNameGenerator(“日志”)
                .backupStrategy(new NeverBackupStrategy())             // Default: FileSizeBackupStrategy(1024 * 1024) 默认:FileSizeBackupStrategy(1024 * 1024)
                .cleanStrategy(new FileLastModifiedCleanStrategy(MAX_TIME))     // Default: NeverCleanStrategy() 默认值:NeverCleanStrategy ()
                .flattener(new DefaultFlattenerInfo())                          // Default: DefaultFlattener 默认值:DefaultFlattener
                .build();
        xToolLogger = XLog.printers(filePrinter).build();
    }
}`

App Module
`public class AppTools {
    private static volatile AppTools sInstance;
    private static final long MAX_TIME = 1L * 24L * 60L * 60L * 1000L;
    private Logger xToolLogger;

    public Logger getxToolLogger() {
        return xToolLogger;
    }

    public void setxToolLogger(Logger xToolLogger) {
        this.xToolLogger = xToolLogger;
    }

    //单例模式
    public static AppTools instance() {
        if (sInstance == null) {
            synchronized (AppTools.class) {
                if (sInstance == null) {
                    sInstance = new AppTools();
                }
            }
        }
        return sInstance;
    }

    public AppTools() {
        String xlogPath = "/sdcard/applog/log1/";
        Printer filePrinter = new FilePrinter                      // Printer that print(save) the log to file 打印(保存)日志到文件的打印机
                .Builder(xlogPath)                         // Specify the directory path of log file(s) 指定日志文件的目录路径
                .fileNameGenerator(new DateFileNameGenerator())        // Default: ChangelessFileNameGenerator("log") 默认值:ChangelessFileNameGenerator(“日志”)
                .backupStrategy(new NeverBackupStrategy())             // Default: FileSizeBackupStrategy(1024 * 1024) 默认:FileSizeBackupStrategy(1024 * 1024)
                .cleanStrategy(new FileLastModifiedCleanStrategy(MAX_TIME))     // Default: NeverCleanStrategy() 默认值:NeverCleanStrategy ()
                .flattener(new DefaultFlattenerInfo())                          // Default: DefaultFlattener 默认值:DefaultFlattener
                .build();
        xToolLogger = XLog.printers(filePrinter).build();
    }
}`

不知道这样写好不好

**Comment by ichtj** [comment]
其实我的想法是每个module 全局弄一个日志记录的Logger,而不是每一个module中的java文件都创建一个Logger来记录

**Comment by elvishew** [comment]
> 其实我的想法是每个module 全局弄一个日志记录的Logger,而不是每一个module中的java文件都创建一个Logger来记录 即：xtoolsmodule中的所有java文件的打印 调用XTools.instance().getxToolLogger().d("record log2") 即：App module中的所有java文件的打印 调用AppTools.instance().getxToolLogger().d("record log1")

You are right

**Comment by ichtj** [comment]
> > 其实我的想法是每个module 全局弄一个日志记录的Logger,而不是每一个module中的java文件都创建一个Logger来记录 即：xtoolsmodule中的所有java文件的打印 调用XTools.instance().getxToolLogger().d("record log2") 即：App module中的所有java文件的打印 调用AppTools.instance().getxToolLogger().d("record log1")
> 
> You are right

好的 感谢
