### ISSUE TITLE
Pretty TimeStamp

### ISSUE THREAD

**Issue by Isanderthul** [elvishew/xLog#13]
Is there any way to change default timestamp from epoch to date string
1486381070403|D|X-LOG|Simple message
to 
Mon, 06 Feb 2017 11:37:50.403 GMT|D|X-LOG|Simple message

**Comment by elvishew** [comment]
@Isanderthul Take a look at `ClassicFlattener` or `PatternFlattener`, and specify the log flattener using `FilePrinter.Builder.logFlattener(Flattener)`. With `Flattener`, you can totally customize the format of your log.

**Comment by iadcialim** [comment]
Can we create an API or param to easily change the format of the timestamp without subclassing PatternFlattener?
We just want to set the format of the timestamp, the rest of the implementations are ok.
