### ISSUE TITLE
打印时, 前面有 TAG , 只打印 TAG?

### ISSUE THREAD

**Issue by jp1017** [elvishew/xLog#16]
```
XLog.w("MYTAG", "hello klog");
```

只打印 MYTAG, 后面没有了??

**Comment by elvishew** [comment]
@jp1017 You used the wrong method. Use `XLog.tag("MYTAG").w("hello klog");` instead.

**Comment by jp1017** [comment]
但是按照我的代码书写， 怎么破？

**Comment by elvishew** [comment]
@jp1017 If you want to make your old codes work, please refer to [Migration]( https://github.com/elvishew/xLog#migration)

**Comment by Aeiric** [comment]
im sorry for asking the closed question,cause i got the same problem. i was sure used the right code 
like " XLog.tag(tag).e(content)" but only shows the global tag and the custom tag,no content...what's wrong,thanks for your answer~

**Comment by elvishew** [comment]
@Aeiric I think maybe you didn't actually use the `XLog.tag(tag).e(content)`. Are you using some wrappers? Could you try a smallest demo to test your code?
