### ISSUE TITLE
About stack trace info

### ISSUE THREAD

**Issue by whyalwaysmea** [elvishew/xLog#17]
Sometime I defined my L.java, and I use XLog in L.java.
 L.java have some methods, example: 
```java
public static void e(String contents) {
    log(contents);
}

private static void log(String contents) {
    XLog.e(contents);
}
```
then I use L.java in MainActivity
```java
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        L.e("Hello World");
}
```

I set st(3), and the log is :
>├ com.whyalwaysmea.basemodule.L.log(L.java:156)
║	├ com.whyalwaysmea.basemodule.L.e(L.java:127)
║	└ com.whyalwaysmea.diycode.MainActivity.onCreate(MainActivity.java:23)

Can I only see the last Info(MainActivity.java)? how to do it?
Thanks.

**Comment by elvishew** [comment]
@whyalwaysmea For your case, you can use `st("com.whyalwaysmea.basemodule.L", 3) when you initialize the logger, with the latest release(1.4.0).

**Comment by elvishew** [comment]
1.4.0 released
