### ISSUE TITLE
Customizable log levels

### ISSUE THREAD

**Issue by verheyenkoen** [elvishew/xLog#18]
I'm looking for a way to customize log levels. E.g. we don't use `verbose` but we do use `critical` (higher than error). Currently all I can do is "transpose" the log levels with a wrapper and an interceptor or something making everything a mess (and stack traces incorrect because the wrapper is irrelevant).

**Comment by elvishew** [comment]
@verheyenkoen Can you show part of the code("transpose" the log levels with a wrapper and an interceptor) so I can understand what you want better?

**Comment by verheyenkoen** [comment]
@elvishew I don't actually do it as it's ugly, but I mean some kind of Log class that wraps around XLog with methods that would look like this:

```
public static void v(...) {
    XLog.d(...);
}
```

**Comment by elvishew** [comment]
@verheyenkoen Sounds cool, I will do it.

**Comment by elvishew** [comment]
@verheyenkoen It is available in the latest release(1.4.0).
