### ISSUE TITLE
some confusion about filePrinter

### ISSUE THREAD

**Issue by softmicro929** [elvishew/xLog#19]
The xLog is very powerful and pretty, i am excited in using it.
but when i use the function of printing log to the sdcrad,  i meet some question.
for example,when i use a globalFilePrinter and a LocalFilePrinter in the same time,and set the file path same,and the filename generator by date as also, it would't create two log file, they will write in a same file. is it a BUG?
in another case, I just use a globalFilePrinter,then  it will create one log file, does the xLog has the ability to clear the log file automatically ？ If not ,the log file will be very large.

**Comment by elvishew** [comment]
@softmicro929 
1. Two printers, same file. I think you can specify different path for these two printers. For example, printer1 write logs in "/your_path/printer1/", printer2 write logs in "/your_path/printer2/", so even you use the same filename generator(by date) they won't write in a same file.
2. Currently, xLog doesn't provide a method for clearing log files. For your problem, single log file seems to be very large, you can specify a backup strategy(FilePrinter.Builder#backupStrategy) for your file printer, I think it can fix your problem.

**Comment by softmicro929** [comment]
@elvishew 
Get it. I didn't notice the backupStrategy.Thank you.

**Comment by elvishew** [comment]
`CleanStrategy` is supported since version [1.5.0](https://github.com/elvishew/xLog/releases/tag/1.5.0)
