### ISSUE TITLE
如何关闭log输出

### ISSUE THREAD

**Issue by sword30021** [elvishew/xLog#2]
开发阶段需要输出log，产品上线后想关闭，有这个的方法吗？

**Comment by elvishew** [comment]
I think you can try something like this:
`XLog.init(BuildConfig.DEBUG ? LogLevel.ALL : LogLevel.NONE);`

**Comment by jp1017** [comment]
> I think you can try something like this:
> XLog.init(BuildConfig.DEBUG ? LogLevel.ALL : LogLevel.NONE);


同时要配置下调试开关，默认的就可以，如下:

```
    buildTypes {
        release {
            debuggable false
            ......
        }
        debug {
            ......
            debuggable true
        }
    }
```

**Comment by elvishew** [comment]
@sword30021 By default, the debug build is debuggable and the release build is not, so no need to configure the debuggable manually.

**Comment by elvishew** [comment]
@jp1017 By default, the debug build is debuggable and the release build is not, so no need to configure the debuggable manually.

**Comment by jp1017** [comment]
Yes. Aha.
