### ISSUE TITLE
log backup

### ISSUE THREAD

**Issue by xiaoqingxu0502** [elvishew/xLog#21]
Hi，I know Xlog is great，but I incomprehension why there is a log backup function，If you can tell me It applies to which scenes？I will be very grateful.

**Comment by elvishew** [comment]
@xiaoqingxu0502 The backup feature can prevent a log file being too big, you can specify a backup strategy to tell XLog when to backup the old log file and start a new log file

**Comment by xiaoqingxu0502** [comment]
Oh, thanks very much，I get it。
