### ISSUE TITLE
how can I change log level after initiation?

### ISSUE THREAD

**Issue by a1onexiang2** [elvishew/xLog#25]
I initialize XLog in my project by code:
```java
XLog.init(new LogConfiguration.Builder()
                .logLevel(Config.isLogEnabled() ? LogLevel.ALL : LogLevel.NONE)
                .t()
                .st(3)
                .b()
                .build());
```
The log level is set to `LogLevel.NONE` in release version, but I have a secret log switch to debug something, so, how can I change log level after XLog initialized?

**Comment by elvishew** [comment]
@a1onexiang2 Can you just change your code to the below?
```java
XLog.init(new LogConfiguration.Builder()
                .logLevel((Config.isLogEnabled() || isDebugSwitchOn()) ? LogLevel.ALL : LogLevel.NONE)
...
```
But it only work after you restart your app.

Otherwise, you can modify the `LogConfiguration.logLevel` with java reflecting

**Comment by a1onexiang2** [comment]
@elvishew Thanks and I did have fixed it as you suggested. But as you said following, I have to restart my app to make it work. The point is "Is there another way to make it work immediately without restart?"

**Comment by elvishew** [comment]
@a1onexiang2 As I mentioned, you can modify the `LogConfiguration.logLevel` of global or partial `Logger` with java reflecting, I think that's the only way to make it work without restart.

**Comment by JarenFeng** [comment]
@elvishew its not easy to modify the `logLevel ` filed by java reflecting as its modified with ‘`final`’

**Comment by elvishew** [comment]
Please refer to #30 , maybe it will help
