### ISSUE TITLE
save log file names by tag?

### ISSUE THREAD

**Issue by yongchen77** [elvishew/xLog#26]
is it possible to save log file names by tag?

**Comment by elvishew** [comment]
It is not possible currently, but there is a workaround, you can use different `Logger`s (with different tags) to save to different files.

e.g:
```java
Logger loggerA = XLog.tag("tagA").printers(...filePrinterSavingToFileA).build();
loggerA.d("msgA");
...
Logger loggerB = XLog.tag("tagB").printers(...filePrinterSavingToFileB).build();
loggerB.d("msgB");
...
```

Hope this help you

**Comment by yongchen77** [comment]
Thanks.
