### ISSUE TITLE
日志格式有点别扭

### ISSUE THREAD

**Issue by MAIMIHO** [elvishew/xLog#27]
老哥, 你好, 
    logcat打印的日志第一行的边框和和下面的没有对齐. 能否更改一下. 
![image](https://user-images.githubusercontent.com/18633356/32264451-b398d80a-bf19-11e7-8c3d-4b600b552232.png)

**Comment by DysaniazzZ** [comment]
+1，对不齐的问题如何解决？

**Comment by elvishew** [comment]
> +1，对不齐的问题如何解决？

Use `AndroidPrinter(true)` and see if it is what you want
