### ISSUE TITLE
库不错，木demo？

### ISSUE THREAD

**Issue by jp1017** [elvishew/xLog#3]
:smile:

**Comment by elvishew** [comment]
@jp1017 The most usages have been listed in the README already. Anyway, will add a sample in future.

**Comment by ssyijiu** [comment]
Thanks for you library. In long json print you library is better than Logger.

**Comment by elvishew** [comment]
@jp1017 A simple sample is added.

**Comment by jp1017** [comment]
Wow, see it, great job, :+1: :smile:
