### ISSUE TITLE
日志会打印两次

### ISSUE THREAD

**Issue by zhaoxiuyu** [elvishew/xLog#35]
日志输出会打印两次
一次是 X-Log     一次是System.out

![biz2n jm 71 gpcm b_i7h](https://user-images.githubusercontent.com/16554580/34719603-5ea0fcc2-f576-11e7-8b7c-3f26d2f3863e.png)

**Comment by elvishew** [comment]
@zhaoxiuyu If you don't want the "System.out" log, please remove `ConsolePrinter` when initializing.

**Comment by song314** [comment]
@elvishew well, but what is the ConsolePrinter design for ？JSE？

**Comment by elvishew** [comment]
@song314 Mostly, yes
