### ISSUE TITLE
调用 json 方法崩溃了

### ISSUE THREAD

**Issue by RockyQu** [elvishew/xLog#36]
在 JSONObject JSONArray 同时有互相包含时的情况

**Comment by elvishew** [comment]
@RockyQu I am not quite sure what you mean, can you paste your JSON example here?

**Comment by RockyQu** [comment]
JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("a","b");
            jsonObject.put("aasasf","bag");
            jsonObject.put("aadg","badga");
            jsonObject.put("adg",true);

            JSONArray jsonArray = new JSONArray();
            JSONObject jsonObject1 = new JSONObject();
            jsonObject1.put("a","b");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("c","asfadged");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("a",1);
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("r",3.141586521156);
            jsonArray.put(jsonObject1);

            jsonObject.put("array",jsonArray);
        } catch (JSONException e) {
            e.printStackTrace();
        }

**Comment by RockyQu** [comment]
JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("a","b");
            jsonObject.put("aasasf","bag");
            jsonObject.put("aadg","badga");
            jsonObject.put("adg",true);

            JSONArray jsonArray = new JSONArray();
            JSONObject jsonObject1 = new JSONObject();
            jsonObject1.put("a","b");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("c","asfadged");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("a",1);
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("r",3.141586521156);
            jsonArray.put(jsonObject1);

            jsonObject.put("array",jsonArray);
        } catch (JSONException e) {
            e.printStackTrace();
        }

**Comment by RockyQu** [comment]
public static String getJson() {
        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("a","b");
            jsonObject.put("aasasf","bag");
            jsonObject.put("aadg","badga");
            jsonObject.put("adg",true);

            JSONArray jsonArray = new JSONArray();
            JSONObject jsonObject1 = new JSONObject();
            jsonObject1.put("a","b");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("c","asfadged");
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("a",1);
            jsonArray.put(jsonObject1);

            jsonObject1 = new JSONObject();
            jsonObject1.put("r",3.141586521156);
            jsonArray.put(jsonObject1);

            jsonObject.put("array",jsonArray);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return jsonObject.toString();
    }

**Comment by RockyQu** [comment]
上面的这段

**Comment by elvishew** [comment]
@RockyQu The code you pasted seems okay, and I run it on my android phone, it works.
```
{
    "a": "b",
    "aasasf": "bag",
    "aadg": "badga",
    "adg": true,
    "array": [
        {
            "a": "b"
        },
        {
            "c": "asfadged"
        },
        {
            "a": 1
        },
        {
            "r": 3.141586521156
        }
    ]
}
```
Can you try again the code above, or tell more details about the problem you are suffering?
