### ISSUE TITLE
动态的设置TAG

### ISSUE THREAD

**Issue by caozhx** [elvishew/xLog#44]
在不同的类里面设置不用的TAG，不想使用局部的用法，每次设置很多参数太麻烦，怎样实现动态设置TAG

**Comment by elvishew** [comment]
@caozhx Currently there is not a simple way to do that, but I think you don't need to set 'a lot of' parameters every time, setting the tag is enough.
For example, you have already fully initialized xLog in you `Application.onCreate`, you just need to define a partial logger at the beginning of your class.
```java
private static final LOGGER = XLog.tag(className).build();
```
And use this `LOGGER` in the class.

Yes, it is a little troublesome
