### ISSUE TITLE
文件日志能否添加清理功能，比如最多保留多少天的

### ISSUE THREAD

**Issue by jebai0521** [elvishew/xLog#45]

**Comment by dotfeng** [comment]
https://github.com/elvishew/xLog/pull/41

**Comment by hugbio** [comment]
框架现有的功能好像无法实现，不过可以通过自定义FileNameGenerator来实现。
`
public class MyFileNameGenerator implements FileNameGenerator {
    private static final String FILE_NAME_PREFIX = "xLog";
    private static final String FORMAT = "txt";
    private final String fileDir;
    private final int maxCacheSize;
    private final int maxFileSize;
    private volatile String curFileName;
    private volatile long curCacheSize;   //不包括正在写入的日志文件

    public MyFileNameGenerator(String fileDir, int maxCacheSize, int maxFileSize) {
        this.fileDir = fileDir;
        this.maxCacheSize = maxCacheSize;
        this.maxFileSize = maxFileSize;
    }

    @Override
    public boolean isFileNameChangeable() {
        return true;
    }

    @Override
    public String generateFileName(int logLevel, long timestamp) {
        if (TextUtils.isEmpty(curFileName) || !FileUtils.isFileExists(fileDir + File.separator + curFileName)) {  //第一次需要分析缓存目录，初始化必要的数据
            curFileName = null;
            checkCacheDir(timestamp);
        }
        if (TextUtils.isEmpty(curFileName)) {
            curFileName = getFileNameForUnique(timestamp);
            curCacheSize = 0;
        } else {
            long fileSize = FileUtils.getFileSize(fileDir + File.separator + curFileName);
            while (curCacheSize + fileSize >= maxCacheSize) {  //超过最大缓存限制。需要删除最早的日志文件
                File oldFile = getOldFile();
                if (oldFile == null) {
                    break;
                }
                if (oldFile.getName().equals(curFileName)) {  //删除当前日志文件
                    if (FileUtils.deleteFile(oldFile)) {
                        curFileName = null;
                        fileSize = 0;
                    } else {
                        break;
                    }
                } else {
                    long deleteSize = FileUtils.getFileSize(oldFile);
                    if (FileUtils.deleteFile(oldFile)) {
                        if (deleteSize > 0) {
                            curCacheSize = curCacheSize - deleteSize;
                            if (curCacheSize < 0) {
                                curCacheSize = 0;
                            }
                        }
                    } else {
                        break;
                    }
                }
            }
            if (fileSize >= maxFileSize) {//超过最大单文件大小限制。需要分文件
                curFileName = getFileNameForUnique(timestamp);
                curCacheSize += fileSize;
            } else {
                if (TextUtils.isEmpty(curFileName)) {
                    curFileName = getFileNameForUnique(timestamp);
                }
            }
        }
        return curFileName;
    }

    private void checkCacheDir(long timestamp) {
        List<File> files = getCacheFileList();
        if (files == null || files.size() == 0) {
            curCacheSize = 0;
            curFileName = getFileNameForUnique(timestamp);
            return;
        }
        long size = 0;
        File lastFile = null;
        long lastFileModified = Long.MIN_VALUE;
        for (int i = 0; i < files.size(); i++) {
            long fileLastModified = FileUtils.getFileLastModified(files.get(i));
            if (fileLastModified > lastFileModified) {
                lastFileModified = fileLastModified;
                lastFile = files.get(i);
            } else {
                size += FileUtils.getFileSize(files.get(i));
            }
        }
        curCacheSize = size;
        curFileName = lastFile != null ? lastFile.getName() : getFileNameForUnique(timestamp);
    }

    /**
     * 获取最早的日志文件
     */
    private File getOldFile() {
        List<File> files = getCacheFileList();
        if (files == null || files.size() == 0) {
            return null;
        }
        File oldFile = null;
        long oldFileModified = Long.MAX_VALUE;
        for (int i = 0; i < files.size(); i++) {
            long fileLastModified = FileUtils.getFileLastModified(files.get(i));
            if (fileLastModified < oldFileModified) {
                oldFileModified = fileLastModified;
                oldFile = files.get(i);
            }
        }
        return oldFile;
    }

    private List<File> getCacheFileList() {
        return FileUtils.listFilesInDirWithFilter(fileDir, new FileFilter() {
            @Override
            public boolean accept(File pathname) {
                String name = pathname.getName();
                return name.startsWith(FILE_NAME_PREFIX) && name.endsWith("." + FORMAT);
            }
        });
    }

    /**
     * 生成一个新的文件名，并保证新的文件不存在
     */
    private String getFileNameForUnique(long timestamp) {
        String fileName = formatFileName(timestamp, 0);
        Random random = new Random();
        while (FileUtils.isFileExists(fileDir + File.separator + fileName)) {
            fileName = formatFileName(timestamp, random.nextInt(10000));
        }
        return fileName;
    }

    private String getDataFormat(long timestamp) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        sdf.setTimeZone(TimeZone.getDefault());
        return sdf.format(new Date(timestamp));
    }

    private String formatFileName(long timestamp, int random) {
        if (random > 0) {
            return FILE_NAME_PREFIX + "_" + getDataFormat(timestamp) + "_" + random + "." + FORMAT;
        } else {
            return FILE_NAME_PREFIX + "_" + getDataFormat(timestamp) + "." + FORMAT;
        }
    }
}
`

由于有可能需要删除当前正在使用的日志文件。如果直接使用框架中的FilePrinter有可能会出现日志无法写入文件的问题。需要修改FilePrinter文件中的一处代码来解决（其实这应该算框架的一个bug吧。如果手动删除了正在使用的日志文件也会出现这个问题。）
修改：
 `
void doPrintln(int logLevel, String tag, String msg) {

      if (!newFileName.equals(lastFileName) || !writer.getFile().exists()) { //如果文件不存在了也关闭并重新创建文件
        if (writer.isOpened()) {
          writer.close();
        }
        if (!writer.open(newFileName)) {
          return;
        }
        lastFileName = newFileName;
      }
    }

  }
`

**Comment by elvishew** [comment]
@hugbio Maybe `FileSizeBackupStrategy` meet your requirement? It will create a new log file when the log file grown too large, and rename the old log file to .bak file

**Comment by williamwue** [comment]
@jebai0521  @dotfeng The function you want is added and you can use it by newest code (#41)

**Comment by elvishew** [comment]
Use a `CleanStrategy` when you initialize the `FilePrinter` since v1.5.0
