### ISSUE TITLE
how to encrypt logs

### ISSUE THREAD

**Issue by zubairehman** [elvishew/xLog#52]
Hi,
First of all thanks for such a wonderful library.
How can i encrypt/decrypt logs using this library. I want to store and read logs from encrypted file, so that normal user can't read the logs. One way is to add them in (.Folder) but still a user can access the files

**Comment by elvishew** [comment]
@zubairehman I guess what you ask is "How to encrypt/decrypt logs using FilePrinter of this library", right?
From what I can imagine, you can implement your own `Flattener` when initializing `FilePrinter`.

You have two choices:
1. Completely implement a `Flattener`.
```java
class EncryptedFlattener implement Flattener {
  public CharSequence flatten(int logLevel, String tag, String message) {
    String flattenedLog;
    ... // Flatten the log
    return encrypt(flattenedLog); // Use any symmetric encryption algorithm you like
  }
}
```
2. Extend `ClassicFlattener` or `PatternFlattener`
```java
public CharSequence flatten(int logLevel, String tag, String message) {
  String flattenedLog = super.flatten(logLevel, tag, message);
  return encrypt(flattenedLog); // Use any symmetric encryption algorithm you like
}
```

Hope this help you
