### ISSUE TITLE
超长Json数据丢失问题

### ISSUE THREAD

**Issue by sfshine** [elvishew/xLog#56]
![_ _20181015155555](https://user-images.githubusercontent.com/3046831/46937109-f5a78800-d092-11e8-8b38-525651e818dc.png)

**Comment by elvishew** [comment]
@sfshine Can you tell which version of xLog do you use?

**Comment by FamliarMan** [comment]
same problem

**Comment by elvishew** [comment]
@sfshine @FamliarMan Can you try to use `new AndroidPrinter(int maxChunkSize)` instead of `new AndroidPrinter()`, and specify a reasonable chunk size for example `2000` or `3000` (which is less than `4063` - the default one) to see if this issue can be fixed?

**Comment by FamliarMan** [comment]
@elvishew  It works fine when I use 2000.
