### ISSUE TITLE
logcat中app相关的系统日志或者第三方库的日志能记录到吗

### ISSUE THREAD

**Issue by Alvin9234** [elvishew/xLog#58]
我看了一下日志输出和存储后的内容，这个只存储了我调用XLog.e，XLog.i地方输出的内容，而Android Studio的logcat中有很多和app有关的日志输出（比如第三方库的一些日志，解析异常等），我想把这些也存储起来，更方便全面分析日志，这个可以实现吗

**Comment by Alvin9234** [comment]
The log library only records the log output of the method that I called XLog.i(). In fact, there are many APP-related logs in Logcat, and many of them are useful. For example, the third SDK will also report some logs, how to put these Other system logs related to APP are also recorded.

**Comment by elvishew** [comment]
@Alvin9234 Recording all logs printed by system seems great, but since xLog is a light-weight library, it is mostly designed to print your own logs conveniently, not for collecting system logs, maybe you can collect by yourself and save the logs to file using `FilePrinter#println`

**Comment by elvishew** [comment]
Finally, [LibCat](https://github.com/elvishew/XLog/blob/master/xlog-libcat) allow you to intercept the logs from third party libraries within SAME app.

And still can not get the logs from other app.
