### ISSUE TITLE
The border can't alignment[边框线不能对齐].

### ISSUE THREAD

**Issue by ghost** [elvishew/xLog#62]
When I used the XLog to print log message with '.b',the border can't alignment.
[当我使用带有-b参数的XLog打印日志信息的时候,边框线不能对齐]
![2018-11-29_141650](https://user-images.githubusercontent.com/43057595/49203115-03666200-f3e2-11e8-91e1-e6a65246014b.png)

I found that my question is identical with #50 ,I wish author can update the XLog to new version Android Studio.

**Comment by elvishew** [comment]
@amColinzzz xLog can not do more about this issue, it depends on how android studio display the log.
Please refer to the solution of #50
