### ISSUE TITLE
有个Bug

### ISSUE THREAD

**Issue by a1018875550** [elvishew/xLog#7]
当我这样使用时`  XLog.e(TAG , "LOG");` 他只输出前面的tag,不输出后面的Log

**Comment by elvishew** [comment]
@a1018875550 I think you are using XLog in the wrong way. There is no such a `XLog.e(TAG , "LOG")`, but a `XLog.e(String format, Object... args)`, if you want to log an error, you can just `XLog.e("LOG")`, or if you want to specify a log-based tag, you can `XLog.tag(TAG).e("LOG")`.
Hope this can help you.

**Comment by a1018875550** [comment]
thanks!
