### ISSUE TITLE
xLog was crashed

### ISSUE THREAD

**Issue by lantsang** [elvishew/xLog#72]
Hi, I used a schedule service to get data from network on every 5 seconds,  printing logs during the process, sometimes the log was crashed with nothing.
I have uploaded the screenshot [here](https://lantsang.net/image/crashed_log.png), thanks for your help.

**Comment by elvishew** [comment]
@lantsang I can't understand, where is the crash, and was it caused by xlog?

**Comment by elvishew** [comment]
No more feedback, seems same as #70
