### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by coxfilur** [elvishew/xLog#76]
07-22 15:45:36.184 E/AndroidRuntime( 7853): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.Writer.write(java.lang.String)' on a null object reference
07-22 15:45:36.184 E/AndroidRuntime( 7853): 	at com.elvishew.xlog.printer.file.FilePrinter$b.b(FilePrinter.java:481)
07-22 15:45:36.184 E/AndroidRuntime( 7853): 	at com.elvishew.xlog.printer.file.FilePrinter.a(FilePrinter.java:1152)
07-22 15:45:36.184 E/AndroidRuntime( 7853): 	at com.elvishew.xlog.printer.file.FilePrinter$a.run(FilePrinter.java:361)
07-22 15:45:36.184 E/AndroidRuntime( 7853): 	at java.lang.Thread.run(Thread.java:764)

**Comment by zztmercury** [comment]
I got same crash

**Comment by elvishew** [comment]
Does it happen frequently?

**Comment by yujiangtao668** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.write(java.lang.String)' on a null object reference at com.elvishew.xlog.printer.file.FilePrinter$Writer.null a(null)(FilePrinter.java:2) at com.elvishew.xlog.printer.file.FilePrinter.null b(null)(FilePrinter.java:143) at com.elvishew.xlog.printer.file.FilePrinter$Worker.null run(null)(FilePrinter.java:18) at java.lang.Thread.null run(null)(Thread.java:919)

**Comment by yujiangtao668** [comment]
this crash happend on android Api 29
![image](https://user-images.githubusercontent.com/49176982/100038443-e8971e80-2e3e-11eb-8f9c-b538db8656dd.png)

**Comment by elvishew** [comment]
Tracked in #70
