### ISSUE TITLE
Android 10(Q)的适配

### ISSUE THREAD

**Issue by howtoplay** [elvishew/xLog#78]
Android 10(Q)的存储机制完全变了，希望作者大大能尽快适配

**Comment by elvishew** [comment]
@howtoplay Is there any problem you are suffering with Android 10?

**Comment by howtoplay** [comment]
I can not print the log to external storage on Android 10

**Comment by elvishew** [comment]
@howtoplay When constructing a `FilePrinter`, you can use a folder path like `Context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)`, your app would have the access permission
