### ISSUE TITLE
Device list window popup not displaying on Android Studio 3.5.2

### ISSUE THREAD

**Issue by raviyadav5951** [elvishew/xLog#79]
Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 31, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by elvishew** [comment]
Not related to the library
