### ISSUE TITLE
日志文件用什么打开查看呢

### ISSUE THREAD

**Issue by ChenBu2** [elvishew/xLog#80]
日志文件用什么打开呢

**Comment by zak-ml** [comment]
请问你有看到生成的日志文件吗，我在 /Android/data/packageName/ 下面没看到生成的日志文件，调试 FilePrinter 发现 Worker 线程也是完成了写文件的操作。

**Comment by zak-ml** [comment]
> 日志文件用什么打开呢

请问你有看到生成的日志文件吗，我在 /Android/data/packageName/ 下面没看到生成的日志文件，调试 FilePrinter 发现 Worker 线程也是完成了写文件的操作。

**Comment by zak-ml** [comment]
> > 日志文件用什么打开呢
> 
> 请问你有看到生成的日志文件吗，我在 /Android/data/packageName/ 下面没看到生成的日志文件，调试 FilePrinter 发现 Worker 线程也是完成了写文件的操作。

路径取错了

**Comment by elvishew** [comment]
@ChenBu2 A log file is a simple text file, any text viewer can open it as Text
