### ISSUE TITLE
打印字符串长度超过4053个字符就会丢失10个字符左右

### ISSUE THREAD

**Issue by qiubin2016** [elvishew/xLog#85]
XLog.init(LogLevel.ALL);
Logger xlog = XLog.tag(TAG).build();
String string = "00000000000000001111111";  //超过4053个字符就会丢失字符，最多丢失10个字符，会自动换行打印；
xlog.i(string);

**Comment by elvishew** [comment]
@qiubin2016 What device did you test on?
Besides, you can use `new AndroidPrinter(int maxChunkSize)` instead on `new AndroidPrinter()`, and specify a safe chunk size, for example 4053.

**Comment by elvishew** [comment]
Change default chunk size to 4000 in release [1.7.0](https://github.com/elvishew/xLog/releases/tag/1.7.0)
