### ISSUE TITLE
为什么打印出来的时间格式时时间戳，在哪里可以配置？

### ISSUE THREAD

**Issue by ginkwang** [elvishew/xLog#88]
`    private void initLog() {
        LogConfiguration config = new LogConfiguration.Builder()
                .tag("PROTOCOL_TAG")
                .st(2)
                .t()
                .b()
                .build();

        Printer androidPrinter = new AndroidPrinter();
        Printer consolePrinter = new ConsolePrinter();
        Printer filePrinter = new FilePrinter
                .Builder("/sdcard/AutoProtocolLog/")
                .fileNameGenerator(new DateFileNameGenerator())
                .backupStrategy(new NeverBackupStrategy())
                .build();

        XLog.init(config, androidPrinter, consolePrinter, filePrinter);
    }`

使用
XLog.i("destory");

**Comment by elvishew** [comment]
#13
