### ISSUE TITLE
 A frequent crash on API 29

### ISSUE THREAD

**Issue by yujiangtao668** [elvishew/xLog#92]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.write(java.lang.String)' on a null object reference at com.elvishew.xlog.printer.file.FilePrinter$Writer.null a(null)(FilePrinter.java:2) at com.elvishew.xlog.printer.file.FilePrinter.null b(null)(FilePrinter.java:143) at com.elvishew.xlog.printer.file.FilePrinter$Worker.null run(null)(FilePrinter.java:18) at java.lang.Thread.null run(null)(Thread.java:919)
![image](https://user-images.githubusercontent.com/49176982/100039237-c81b9400-2e3f-11eb-821f-68e806ce9fa1.png)

**Comment by elvishew** [comment]
@yujiangtao668 Can you tell what path do you save the logs into? Maybe there is something different in android 29, but need some further investigation.

**Comment by yujiangtao668** [comment]
@elvishew sdcard/Android/data/com.xx.xxx/files/log/xx.txt   This is the internal storage address of the phone, there should be no problem, right?

**Comment by yujiangtao668** [comment]
![image](https://user-images.githubusercontent.com/49176982/101598740-973c8100-3a33-11eb-801d-488e86982446.png)

**Comment by elvishew** [comment]
Track in #70
