### ISSUE TITLE
[Question] Are logs readable by  specific formats

### ISSUE THREAD

**Issue by LiorBanai** [elvishew/xLog#94]
Hi,
I was wondering if it worth adding reading/parsing xlog files with my [Log viewer](https://github.com/Analogy-LogViewer/Analogy.LogViewer).
Does your library have parsers (even in Java) to parse the logs or do I need to write custom parsers per log structure?

**Comment by elvishew** [comment]
@LiorBanai The format of xlog is defined by user, there is no such official format, so I think there is no need to "parse" it.

**Comment by LiorBanai** [comment]
Thanks!
